# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.CharField(max_length=60)),
                ('short_link', models.CharField(max_length=30)),
            ],
        ),
    ]
